framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_transaction
            query.bus:
                middleware:
                    - validation
            event.bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_transaction

        transports:
            sync: 'sync://'
            command: 'sync://'
            query: 'sync://'
            event: 'sync://'

        routing:
            'App\Infrastructure\Messenger\CommandInterface': command
            'App\Infrastructure\Messenger\QueryInterface': query
            'App\Infrastructure\Messenger\EventInterface': event

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
